/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * This part needs to get included in the compilation unit where
 * blocking_handler gets defined due to the way #pragma works.
 */


/** @defgroup CM3_nvic_isrdecls_SAM4L User interrupt service routines (ISR) defaults for Atmel SAM4L series
    @ingroup CM3_nvic_isrdecls

    @{*/

void hflashc_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca0_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca1_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca2_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca3_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca4_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca5_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca6_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca7_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca8_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca9_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca10_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca11_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca12_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca13_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca14_isr(void) __attribute__((weak, alias("blocking_handler")));
void pdca15_isr(void) __attribute__((weak, alias("blocking_handler")));
void crccu_isr(void) __attribute__((weak, alias("blocking_handler")));
void usbc_isr(void) __attribute__((weak, alias("blocking_handler")));
void pevc_tr_isr(void) __attribute__((weak, alias("blocking_handler")));
void pevc_ov_isr(void) __attribute__((weak, alias("blocking_handler")));
void aesa_isr(void) __attribute__((weak, alias("blocking_handler")));
void pm_isr(void) __attribute__((weak, alias("blocking_handler")));
void scim_isr(void) __attribute__((weak, alias("blocking_handler")));
void freqm_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio0_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio1_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio2_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio3_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio4_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio5_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio6_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio7_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio8_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio9_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio10_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpio11_isr(void) __attribute__((weak, alias("blocking_handler")));
void bpm_isr(void) __attribute__((weak, alias("blocking_handler")));
void bscif_isr(void) __attribute__((weak, alias("blocking_handler")));
void ast_alarm_isr(void) __attribute__((weak, alias("blocking_handler")));
void ast_per_isr(void) __attribute__((weak, alias("blocking_handler")));
void ast_ovf_isr(void) __attribute__((weak, alias("blocking_handler")));
void ast_ready_isr(void) __attribute__((weak, alias("blocking_handler")));
void ast_clkready_isr(void) __attribute__((weak, alias("blocking_handler")));
void wdt_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic1_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic2_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic3_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic4_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic5_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic6_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic7_isr(void) __attribute__((weak, alias("blocking_handler")));
void eic8_isr(void) __attribute__((weak, alias("blocking_handler")));
void iisc_isr(void) __attribute__((weak, alias("blocking_handler")));
void spi_isr(void) __attribute__((weak, alias("blocking_handler")));
void tc00_isr(void) __attribute__((weak, alias("blocking_handler")));
void tc01_isr(void) __attribute__((weak, alias("blocking_handler")));
void tc02_isr(void) __attribute__((weak, alias("blocking_handler")));
void tc10_isr(void) __attribute__((weak, alias("blocking_handler")));
void tc11_isr(void) __attribute__((weak, alias("blocking_handler")));
void tc12_isr(void) __attribute__((weak, alias("blocking_handler")));
void twim0_isr(void) __attribute__((weak, alias("blocking_handler")));
void twis0_isr(void) __attribute__((weak, alias("blocking_handler")));
void twim1_isr(void) __attribute__((weak, alias("blocking_handler")));
void twis1_isr(void) __attribute__((weak, alias("blocking_handler")));
void usart0_isr(void) __attribute__((weak, alias("blocking_handler")));
void usart1_isr(void) __attribute__((weak, alias("blocking_handler")));
void usart2_isr(void) __attribute__((weak, alias("blocking_handler")));
void usart3_isr(void) __attribute__((weak, alias("blocking_handler")));
void adcife_isr(void) __attribute__((weak, alias("blocking_handler")));
void dacc_isr(void) __attribute__((weak, alias("blocking_handler")));
void acifc_isr(void) __attribute__((weak, alias("blocking_handler")));
void abdacb_isr(void) __attribute__((weak, alias("blocking_handler")));
void trng_isr(void) __attribute__((weak, alias("blocking_handler")));
void parc_isr(void) __attribute__((weak, alias("blocking_handler")));
void catb_isr(void) __attribute__((weak, alias("blocking_handler")));
void reserved0_isr(void) __attribute__((weak, alias("blocking_handler")));
void twim2_isr(void) __attribute__((weak, alias("blocking_handler")));
void twim3_isr(void) __attribute__((weak, alias("blocking_handler")));
void lcdca_isr(void) __attribute__((weak, alias("blocking_handler")));

/**@}*/

/* Initialization template for the interrupt vector table. This definition is
 * used by the startup code generator (vector.c) to set the initial values for
 * the interrupt handling routines to the chip family specific _isr weak
 * symbols. */

#define IRQ_HANDLERS \
    [NVIC_HFLASHC_IRQ] = hflashc_isr, \
    [NVIC_PDCA0_IRQ] = pdca0_isr, \
    [NVIC_PDCA1_IRQ] = pdca1_isr, \
    [NVIC_PDCA2_IRQ] = pdca2_isr, \
    [NVIC_PDCA3_IRQ] = pdca3_isr, \
    [NVIC_PDCA4_IRQ] = pdca4_isr, \
    [NVIC_PDCA5_IRQ] = pdca5_isr, \
    [NVIC_PDCA6_IRQ] = pdca6_isr, \
    [NVIC_PDCA7_IRQ] = pdca7_isr, \
    [NVIC_PDCA8_IRQ] = pdca8_isr, \
    [NVIC_PDCA9_IRQ] = pdca9_isr, \
    [NVIC_PDCA10_IRQ] = pdca10_isr, \
    [NVIC_PDCA11_IRQ] = pdca11_isr, \
    [NVIC_PDCA12_IRQ] = pdca12_isr, \
    [NVIC_PDCA13_IRQ] = pdca13_isr, \
    [NVIC_PDCA14_IRQ] = pdca14_isr, \
    [NVIC_PDCA15_IRQ] = pdca15_isr, \
    [NVIC_CRCCU_IRQ] = crccu_isr, \
    [NVIC_USBC_IRQ] = usbc_isr, \
    [NVIC_PEVC_TR_IRQ] = pevc_tr_isr, \
    [NVIC_PEVC_OV_IRQ] = pevc_ov_isr, \
    [NVIC_AESA_IRQ] = aesa_isr, \
    [NVIC_PM_IRQ] = pm_isr, \
    [NVIC_SCIM_IRQ] = scim_isr, \
    [NVIC_FREQM_IRQ] = freqm_isr, \
    [NVIC_GPIO0_IRQ] = gpio0_isr, \
    [NVIC_GPIO1_IRQ] = gpio1_isr, \
    [NVIC_GPIO2_IRQ] = gpio2_isr, \
    [NVIC_GPIO3_IRQ] = gpio3_isr, \
    [NVIC_GPIO4_IRQ] = gpio4_isr, \
    [NVIC_GPIO5_IRQ] = gpio5_isr, \
    [NVIC_GPIO6_IRQ] = gpio6_isr, \
    [NVIC_GPIO7_IRQ] = gpio7_isr, \
    [NVIC_GPIO8_IRQ] = gpio8_isr, \
    [NVIC_GPIO9_IRQ] = gpio9_isr, \
    [NVIC_GPIO10_IRQ] = gpio10_isr, \
    [NVIC_GPIO11_IRQ] = gpio11_isr, \
    [NVIC_BPM_IRQ] = bpm_isr, \
    [NVIC_BSCIF_IRQ] = bscif_isr, \
    [NVIC_AST_ALARM_IRQ] = ast_alarm_isr, \
    [NVIC_AST_PER_IRQ] = ast_per_isr, \
    [NVIC_AST_OVF_IRQ] = ast_ovf_isr, \
    [NVIC_AST_READY_IRQ] = ast_ready_isr, \
    [NVIC_AST_CLKREADY_IRQ] = ast_clkready_isr, \
    [NVIC_WDT_IRQ] = wdt_isr, \
    [NVIC_EIC1_IRQ] = eic1_isr, \
    [NVIC_EIC2_IRQ] = eic2_isr, \
    [NVIC_EIC3_IRQ] = eic3_isr, \
    [NVIC_EIC4_IRQ] = eic4_isr, \
    [NVIC_EIC5_IRQ] = eic5_isr, \
    [NVIC_EIC6_IRQ] = eic6_isr, \
    [NVIC_EIC7_IRQ] = eic7_isr, \
    [NVIC_EIC8_IRQ] = eic8_isr, \
    [NVIC_IISC_IRQ] = iisc_isr, \
    [NVIC_SPI_IRQ] = spi_isr, \
    [NVIC_TC00_IRQ] = tc00_isr, \
    [NVIC_TC01_IRQ] = tc01_isr, \
    [NVIC_TC02_IRQ] = tc02_isr, \
    [NVIC_TC10_IRQ] = tc10_isr, \
    [NVIC_TC11_IRQ] = tc11_isr, \
    [NVIC_TC12_IRQ] = tc12_isr, \
    [NVIC_TWIM0_IRQ] = twim0_isr, \
    [NVIC_TWIS0_IRQ] = twis0_isr, \
    [NVIC_TWIM1_IRQ] = twim1_isr, \
    [NVIC_TWIS1_IRQ] = twis1_isr, \
    [NVIC_USART0_IRQ] = usart0_isr, \
    [NVIC_USART1_IRQ] = usart1_isr, \
    [NVIC_USART2_IRQ] = usart2_isr, \
    [NVIC_USART3_IRQ] = usart3_isr, \
    [NVIC_ADCIFE_IRQ] = adcife_isr, \
    [NVIC_DACC_IRQ] = dacc_isr, \
    [NVIC_ACIFC_IRQ] = acifc_isr, \
    [NVIC_ABDACB_IRQ] = abdacb_isr, \
    [NVIC_TRNG_IRQ] = trng_isr, \
    [NVIC_PARC_IRQ] = parc_isr, \
    [NVIC_CATB_IRQ] = catb_isr, \
    [NVIC_RESERVED0_IRQ] = reserved0_isr, \
    [NVIC_TWIM2_IRQ] = twim2_isr, \
    [NVIC_TWIM3_IRQ] = twim3_isr, \
    [NVIC_LCDCA_IRQ] = lcdca_isr
