language: c
script:
  - make
  - make -C tests/gadget-zero

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded

notifications:
  irc:
    channels:
      - "irc.libera.chat#libopencm3"
    use_notice: true
